### ISSUE TITLE
Can't zoom out using touchpad

### ISSUE THREAD

**Issue by asdf2107** [carykh/VirusGame#23]
Zooming in with touchpad is ok, but zooming out just makes everything shake.

**Comment by What42Pizza** [comment]
I'm also having this problem. I messed with some stuff though (mostly just size()) so I thought I broke something but maybe not.

**Comment by BLiu1** [comment]
This problem should be fixed with pull request #9. Just check out the author's branch. I tested it on my 2015 MacBook Pro with macOS Catalina and it worked well for me.

**Comment by What42Pizza** [comment]
Ok thanks!
